// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJEKF0bPgMCIL1_e9-rVmibOV-CKrT_o8',
    appId: '1:327616120494:web:93a07679283b341e394f3f',
    messagingSenderId: '327616120494',
    projectId: 'tyamo-app88',
    authDomain: 'tyamo-app88.firebaseapp.com',
    storageBucket: 'tyamo-app88.firebasestorage.app',
    measurementId: 'G-0CMRDL1NKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDppJi_ZPfz5yigDucfbFg0ujyKAefKjGQ',
    appId: '1:327616120494:android:0e856a2e085c5d80394f3f',
    messagingSenderId: '327616120494',
    projectId: 'tyamo-app88',
    storageBucket: 'tyamo-app88.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhOrAODU486cVjjREe0-XDRKPdNhmaqc',
    appId: '1:327616120494:ios:8c838938ec74c16e394f3f',
    messagingSenderId: '327616120494',
    projectId: 'tyamo-app88',
    storageBucket: 'tyamo-app88.firebasestorage.app',
    iosBundleId: 'com.example.tymao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbhOrAODU486cVjjREe0-XDRKPdNhmaqc',
    appId: '1:327616120494:ios:8c838938ec74c16e394f3f',
    messagingSenderId: '327616120494',
    projectId: 'tyamo-app88',
    storageBucket: 'tyamo-app88.firebasestorage.app',
    iosBundleId: 'com.example.tymao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBJEKF0bPgMCIL1_e9-rVmibOV-CKrT_o8',
    appId: '1:327616120494:web:b842311a7271bb71394f3f',
    messagingSenderId: '327616120494',
    projectId: 'tyamo-app88',
    authDomain: 'tyamo-app88.firebaseapp.com',
    storageBucket: 'tyamo-app88.firebasestorage.app',
    measurementId: 'G-8L020579NF',
  );
}
